<?php

namespace Database\Seeders;

use App\Models\AccountType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AccountTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'id' => (string) Str::uuid(),
                'code' => 'WAL',
                'name' => 'Wallet Account',
                'currency' => 'NGN',
                'account_category' => 'CUSTOMER_DEPOSIT',
                'normal_balance' => 'DEBIT',
                'min_balance' => 0,
                'max_balance' => null,
                'allow_overdraft' => false,
                'overdraft_limit' => 0,
                'accrues_interest' => false,
                'interest_rate' => 0,
                'description' => 'Wallet account for everyday transactions',
                'is_customer_visible' => true,
                'supports_deposit' => true,
                'supports_withdrawal' => true,
                'supports_transfer' => true,
                'requires_kyc' => true,
                'active' => true,
            ],
            [
                'id' => (string) Str::uuid(),
                'code' => 'SAV',
                'name' => 'Savings Account',
                'currency' => 'NGN',
                'account_category' => 'CUSTOMER_DEPOSIT',
                'normal_balance' => 'DEBIT',
                'min_balance' => 0,
                'max_balance' => null,
                'allow_overdraft' => false,
                'overdraft_limit' => 0,
                'accrues_interest' => true,
                'interest_rate' => 2.5,
                'description' => 'Savings account for mid- and long-term balances',
                'is_customer_visible' => true,
                'supports_deposit' => true,
                'supports_withdrawal' => true,
                'supports_transfer' => true,
                'requires_kyc' => true,
                'active' => true,
            ],
            [
                'id' => (string) Str::uuid(),
                'code' => 'COOP',
                'name' => 'Cooperative Account',
                'currency' => 'NGN',
                'account_category' => 'CUSTOMER_DEPOSIT',
                'normal_balance' => 'DEBIT',
                'min_balance' => 0,
                'max_balance' => null,
                'allow_overdraft' => false,
                'overdraft_limit' => 0,
                'accrues_interest' => true,
                'interest_rate' => 4.0,
                'description' => 'Cooperative savings account that supports loan eligibility',
                'is_customer_visible' => true,
                'supports_deposit' => true,
                'supports_withdrawal' => true,
                'supports_transfer' => true,
                'requires_kyc' => true,
                'active' => true,
            ],
            [
                'id' => (string) Str::uuid(),
                'code' => 'JOINT',
                'name' => 'Joint Account',
                'currency' => 'NGN',
                'account_category' => 'CUSTOMER_DEPOSIT',
                'normal_balance' => 'DEBIT',
                'min_balance' => 0,
                'max_balance' => null,
                'allow_overdraft' => false,
                'overdraft_limit' => 0,
                'accrues_interest' => false,
                'interest_rate' => 0,
                'description' => 'Account shared between two or more customers',
                'is_customer_visible' => true,
                'supports_deposit' => true,
                'supports_withdrawal' => true,
                'supports_transfer' => true,
                'requires_kyc' => true,
                'active' => true,
            ],
            [
                'id' => (string) Str::uuid(),
                'code' => 'SAL',
                'name' => 'Salary Account',
                'currency' => 'NGN',
                'account_category' => 'CUSTOMER_DEPOSIT',
                'normal_balance' => 'DEBIT',
                'min_balance' => 0,
                'max_balance' => null,
                'allow_overdraft' => false,
                'overdraft_limit' => 0,
                'accrues_interest' => false,
                'interest_rate' => 0,
                'description' => 'Account for salary credits and employer-linked payments',
                'is_customer_visible' => true,
                'supports_deposit' => true,
                'supports_withdrawal' => true,
                'supports_transfer' => true,
                'requires_kyc' => true,
                'active' => true,
            ],
            [
                'id' => (string) Str::uuid(),
                'code' => 'ESC',
                'name' => 'Escrow Account',
                'currency' => 'NGN',
                'account_category' => 'ESCROW',
                'normal_balance' => 'DEBIT',
                'min_balance' => 0,
                'max_balance' => null,
                'allow_overdraft' => false,
                'overdraft_limit' => 0,
                'accrues_interest' => false,
                'interest_rate' => 0,
                'description' => 'Escrow account for conditional fund holding between parties',
                'is_customer_visible' => true,
                'supports_deposit' => true,
                'supports_withdrawal' => false,
                'supports_transfer' => false,
                'requires_kyc' => true,
                'active' => true,
            ],
            [
                'id' => (string) Str::uuid(),
                'code' => 'LOAN',
                'name' => 'Loan Account',
                'currency' => 'NGN',
                'account_category' => 'LOAN',
                'normal_balance' => 'CREDIT',
                'min_balance' => 0,
                'max_balance' => null,
                'allow_overdraft' => false,
                'overdraft_limit' => 0,
                'accrues_interest' => false,
                'interest_rate' => 0,
                'description' => 'Customer loan liability account for outstanding loan balances',
                'is_customer_visible' => true,
                'supports_deposit' => false,
                'supports_withdrawal' => false,
                'supports_transfer' => false,
                'requires_kyc' => true,
                'active' => true,
            ],
            [
                'id' => (string) Str::uuid(),
                'code' => 'CURRENT',
                'name' => 'Current Account',
                'currency' => 'NGN',
                'account_category' => 'CUSTOMER_DEPOSIT',
                'normal_balance' => 'DEBIT',
                'min_balance' => 1000,
                'max_balance' => null,
                'allow_overdraft' => true,
                'overdraft_limit' => 50000,
                'accrues_interest' => false,
                'interest_rate' => 0,
                'description' => 'Current account with overdraft facility',
                'is_customer_visible' => true,
                'supports_deposit' => true,
                'supports_withdrawal' => true,
                'supports_transfer' => true,
                'requires_kyc' => true,
                'active' => true,
            ],
            [
                'id' => (string) Str::uuid(),
                'code' => 'TERM',
                'name' => 'Term Deposit Account',
                'currency' => 'NGN',
                'account_category' => 'CUSTOMER_DEPOSIT',
                'normal_balance' => 'DEBIT',
                'min_balance' => 10000,
                'max_balance' => null,
                'allow_overdraft' => false,
                'overdraft_limit' => 0,
                'accrues_interest' => true,
                'interest_rate' => 5.0,
                'description' => 'Fixed term deposit account',
                'is_customer_visible' => true,
                'supports_deposit' => true,
                'supports_withdrawal' => true,
                'supports_transfer' => true,
                'requires_kyc' => true,

        foreach ($types as $type) {
            AccountType::updateOrCreate(
                ['code' => $type['code']],
                $type
            );
        }
    }
}